apiVersion: v1
kind: Service
metadata:
  name: "service-stimulus-challenge"
spec:
  selector:
    app: stimulus-challenge
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80